#!/usr/bin/env bash

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
export BREW_PREFIX=$(brew --prefix)

# System Variables
stty -ixon # Forward bash search
shopt -s direxpand

eval "$(starship init bash)"
PROMPT_COMMAND="history -a;history -r; $PROMPT_COMMAND"

export HISTCONTROL=ignoredups
export HISTTIMEFORMAT='%d/%m/%y %T '
export HISTSIZE=10000
export HISTFILESIZE=10000

export EDITOR="emacsclient --quiet --alternate-editor='emacs --quick'"
export VIEWER="${EDITOR}"

export PYTHONSTARTUP=$HOME/.pythonrc.py
export PIP_CONFIG_FILE=$HOME/.pip.conf
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PATH="${BREW_PREFIX}/sbin:$HOME/.gem/ruby/2.6.0/bin:$PATH"

# Source necessary files
[[ -e "$HOME/.aliases" ]] && . "$HOME/.aliases"
export PATH="${HOME}/bin:${PATH}"

# Java settings
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)

# Ruby
eval "$(rbenv init - bash)"

# Bash
# https://stackoverflow.com/a/14970926
export BASH_COMPLETION_COMPAT_DIR="${BREW_PREFIX}/etc/bash_completion.d"
[[ -r "${BREW_PREFIX}/etc/profile.d/bash_completion.sh" ]] && . "${BREW_PREFIX}/etc/profile.d/bash_completion.sh"
for COMPLETION in "${BREW_PREFIX}/etc/bash_completion.d/"*; do
    [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
done

# Homebrew
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_BAT=1

# Golang
export GOENV=$HOME/.config/go/env
export PATH=$PATH:$(go env GOPATH)/bin
complete -C ~/go/bin/gocomplete go

# Hashicorp
complete -C ${BREW_PREFIX}/bin/terraform terraform
complete -C ${BREW_PREFIX}/bin/vault vault
complete -C ${BREW_PREFIX}/bin/packer packer

eval "$(ssh-agent -s)" >/dev/null 2>&1
ssh-add ~/.ssh/id_ed25519 >/dev/null 2>&1

# AWS
## awscli v2 paginates by default, disable
export AWS_PAGER=""

# Created by `pipx`
export PATH="$PATH:${HOME}/.local/bin"
eval "$(register-python-argcomplete pipx)"

# Node
eval "$(fnm env --use-on-cd)"

source <(kubectl completion bash)

# Work profiles I want to keep out of git
for file in ${HOME}/.work/*; do
    [ -r "${file}" ] && . "${file}"
done

# Rustland
[[ -r "$HOME/.cargo/env" ]] && . "$HOME/.cargo/env"
if command -v rustup > /dev/null; then
    . <(rustup completions bash)
    . <(rustup completions bash cargo)
fi

# ASDF for more specific tool versioning using .tool-versions files
. "$(brew --prefix asdf)/libexec/asdf.sh"
## This was needed to asdf install erlang 24, specifically --without-xw
export KERL_CONFIGURE_OPTIONS="--disable-debug \
                               --disable-hipe \
                               --disable-sctp \
                               --disable-silent-rules \
                               --enable-dynamic-ssl-lib \
                               --enable-kernel-poll \
                               --enable-shared-zlib \
                               --enable-smp-support \
                               --enable-threads \
                               --without-wx
                               --with-ssl=$(brew --prefix openssl@1.1) \
                               --with-wx-config=$(brew --prefix)/bin/wx-config \
                               --without-javac \
                               --without-jinterface \
                               --without-odbc"
